### ISSUE TITLE
Crashes the server on Rift-1.0.4-63.jar

### ISSUE THREAD

**Issue by MSandro** [raphydaphy/BetterBeacons#2]
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at org.dimdev.riftloader.Main.main(Main.java:64) [Rift-1.0.4-63.jar:?]
Caused by: java.lang.NoClassDefFoundError: cjs
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_111]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_111]
        at java.lang.Class.getConstructors(Class.java:1651) ~[?:1.8.0_111]
        at org.dimdev.riftloader.RiftLoader.newInstance(RiftLoader.java:268) ~[RiftLoader.class:?]
        at org.dimdev.riftloader.RiftLoader.loadListeners(RiftLoader.java:250) ~[RiftLoader.class:?]
        at org.dimdev.riftloader.RiftLoader.getListeners(RiftLoader.java:233) ~[RiftLoader.class:?]
        at aeg.handler$onRegisterPotions$zzk000(SourceFile:515) ~[aeg.class:?]
        at aeg.m(SourceFile:276) ~[aeg.class:?]
        at pf.c(SourceFile:463) ~[pf.class:?]
        at net.minecraft.server.MinecraftServer.main(SourceFile:770) ~[MinecraftServer.class:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: cjs
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_111]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_111]
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_111]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_111]
        at java.lang.Class.getConstructors(Class.java:1651) ~[?:1.8.0_111]
        at org.dimdev.riftloader.RiftLoader.newInstance(RiftLoader.java:268) ~[RiftLoader.class:?]
        at org.dimdev.riftloader.RiftLoader.loadListeners(RiftLoader.java:250) ~[RiftLoader.class:?]
        at org.dimdev.riftloader.RiftLoader.getListeners(RiftLoader.java:233) ~[RiftLoader.class:?]
        at aeg.handler$onRegisterPotions$zzk000(SourceFile:515) ~[aeg.class:?]
        at aeg.m(SourceFile:276) ~[aeg.class:?]
        at pf.c(SourceFile:463) ~[pf.class:?]
        at net.minecraft.server.MinecraftServer.main(SourceFile:770) ~[MinecraftServer.class:?]
        ... 7 more
Caused by: java.lang.NullPointerException
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_111]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_111]
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_111]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_111]
        at java.lang.Class.getConstructors(Class.java:1651) ~[?:1.8.0_111]
        at org.dimdev.riftloader.RiftLoader.newInstance(RiftLoader.java:268) ~[RiftLoader.class:?]
        at org.dimdev.riftloader.RiftLoader.loadListeners(RiftLoader.java:250) ~[RiftLoader.class:?]
        at org.dimdev.riftloader.RiftLoader.getListeners(RiftLoader.java:233) ~[RiftLoader.class:?]
        at aeg.handler$onRegisterPotions$zzk000(SourceFile:515) ~[aeg.class:?]
        at aeg.m(SourceFile:276) ~[aeg.class:?]
        at pf.c(SourceFile:463) ~[pf.class:?]
        at net.minecraft.server.MinecraftServer.main(SourceFile:770) ~[MinecraftServer.class:?]
        ... 7 more

**Comment by raphydaphy** [comment]
Thanks for the report - should be fixed in [this commit](https://github.com/raphydaphy/BetterBeacons/commit/73c8bda21956a916c3eb861c7c84d88544da837b), but I can't push a fix until protocharset updates for the new mappings.
